language: python

python:
  - 2.7
  - 3.4

env:
  global:
  - secure: "WLxy9KLb6lVYzW5G8oiCBlbYesZDtAXpJE1ht+cOWMO8CvfcaklcO2VVuHQM3r2yihuH21jNO0JWUXFSzG8DduGCOUhm0/ebvuXDnHeaDh3mZEd+Z/kMX6hF/iP77CrGOk/XWc3cddWoDqywHdQOEBQBL5Oyd7L4DXVIXnIPv/U="

install:
  - conda update --yes conda
  - conda create -n testenv --yes numpy scipy nose pillow matplotlib scikit-image jinja2 pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install libtiff; fi
  - pip install jpype1;
  - export LD_LIBRARY_PATH=/usr/local/lib LIBRARY=ffmpeg;
  - wget https://raw.githubusercontent.com/mikeboers/PyAV/master/scripts/test-setup;
  - bash ./test-setup;
  - pip install av;
  - python setup.py build_ext install


before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; 
    then 
        wget http://repo.continuum.io/miniconda/Miniconda-3.7.3-Linux-x86_64.sh -O miniconda.sh; 
    else 
        wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh; 
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

script:
  - nosetests --nologcapture
  - |
    if [[ $BUILD_DOCS == true ]]; then
      make html --warningsaserrors
    fi

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'soft-matter/pims' && $BUILD_DOCS == true && $TRAVIS_BRANCH == 'master' ]]; then
      cd $TRAVIS_BUILD_DIR
      echo "Uploading documentation"
	  cd .. && git checkout gh-pages && git rm -rf . && touch .nojekyll && mv doc/_build/html/* . && rm -rf doc && git add -A && git commit -a --amend -m "Makefile is force-commiting new build." && git push upstream gh-pages -f
      cd ..
      git clone git@github.com:pims/devdocs.git
      cd devdocs
      git checkout --orphan gh-pages
      git reset --hard first_commit
      cp -R ../pims/doc/build/html/. .
      touch .nojekyll
      git add .
      git commit -m "Docs build of $TRAVIS_COMMIT"
      git push --set-upstream origin gh-pages --force
    fi
